EldredBrown.ProFootball.AspNet.MvcWebApp/Controllers/GamePredictorController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using EldredBrown.ProFootball.AspNet.MvcWebApp.Models.View;
using EldredBrown.ProFootball.AspNet.MvcWebApp.Services;
using log4net;

namespace EldredBrown.ProFootball.AspNet.MvcWebApp.Controllers
{
    /// <summary>
    /// Controller class for the GamePredictor page
    /// </summary>
    public class GamePredictorController : Controller
    {
        #region Member Fields

        private static readonly ILog Log =
            LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private readonly IGamePredictorService _service;
        private readonly ISharedService _sharedService;

        #endregion Member Fields

        #region Constructors & Finalizers

        /// <summary>
        /// Initializes a new instance of the GamePredictorController class
        /// </summary>
        /// <param name="service"></param>
        /// <param name="sharedService"></param>
        public GamePredictorController(IGamePredictorService service, ISharedService sharedService)
        {
            _service = service;
            _sharedService = sharedService;
        }

        #endregion Constructors & Finalizers

        #region Actions

        // GET: GamePredictor
        public async Task<ActionResult> PredictGame()
        {
            try
            {
                await _service.GetGuestAndHostSeasonIds();

                var seasons = await _sharedService.GetSeasonsOrderedAsync();

                ViewBag.GuestSeasonID = new SelectList(seasons, "ID", "ID", GamePredictorService.GuestSeasonID);

                var guestSeasons = await _service.GetEntities((int)GamePredictorService.GuestSeasonID);
                ViewBag.GuestName = new SelectList(guestSeasons, "TeamName", "TeamName");

                ViewBag.HostSeasonID = new SelectList(seasons, "ID", "ID", GamePredictorService.HostSeasonID);

                var hostSeasons = await _service.GetEntities((int)GamePredictorService.HostSeasonID);
                ViewBag.HostName = new SelectList(hostSeasons, "TeamName", "TeamName");

                return View();
            }
            catch (Exception ex)
            {
                Log.Error("Exception in GamePredictorController.PredictGame (GET): " + ex.Message);
                throw;
            }
        }

        /// <summary>
        /// Calculates the predicted score of a future or hypothetical game.
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PredictGame([Bind(Include = "GuestSeasonID,GuestName,HostSeasonID,HostName")] GamePredictionViewModel matchup)
        {
            try
            {
                var seasons = await _sharedService.GetSeasonsOrderedAsync();

                // Show predicted guest score.
                var guestSeason = await _sharedService.FindEntityAsync(matchup.GuestName, matchup.GuestSeasonID);
                ViewBag.GuestSeasonID = new SelectList(seasons, "ID", "ID", guestSeason.SeasonID);

                var guestSeasons = await _service.GetEntities((int)GamePredictorService.GuestSeasonID);
                ViewBag.GuestName = new SelectList(guestSeasons, "TeamName", "TeamName", guestSeason.TeamName);

                // Show predicted host score.
                var hostSeason = await _sharedService.FindEntityAsync(matchup.HostName, matchup.HostSeasonID);
                ViewBag.HostSeasonID = new SelectList(seasons, "ID", "ID", hostSeason.SeasonID);

                var hostSeasons = await _service.GetEntities((int)GamePredictorService.HostSeasonID);
                ViewBag.HostName = new SelectList(hostSeasons, "TeamName", "TeamName", hostSeason.TeamName);

                return View(matchup);
            }
            catch (Exception ex)
            {
                Log.Error("Exception in GamePredictorController.PredictGame (POST): " + ex.Message);
                throw;
            }
        }

        /// <summary>
        /// Applies a filter that allows the user to view only those desired teams
        /// </summary>
        /// <param name="guestSeasonID">The ID of the guest's season</param>
        /// <param name="hostSeasonID">The ID of the host's season</param>
        /// <returns></returns>
        public ActionResult ApplyFilter(int? guestSeasonID, int? hostSeasonID)
        {
            try
            {
                _service.ApplyFilter(guestSeasonID, hostSeasonID);

                return RedirectToAction("PredictGame");
            }
            catch (Exception ex)
            {
                Log.Error("Exception in GamePredictorController.ApplyFilter: " + ex.Message);
                throw;
            }
        }

        #endregion Actions
    }
}

EldredBrown.ProFootball.AspNet.MvcWebApp/Controllers/SeasonStandingsController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using EldredBrown.ProFootball.AspNet.MvcWebApp.Services;
using log4net;

namespace EldredBrown.ProFootball.AspNet.MvcWebApp.Controllers
{
    /// <summary>
    /// Controller class for the SeasonStandings page
    /// </summary>
    public class SeasonStandingsController : Controller
    {
        #region Member Fields

        private static readonly ILog Log =
            LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private readonly ISeasonStandingsService _service;
        private readonly ISharedService _sharedService;

        #endregion Member Fields

        #region Constructors & Finalizers

        /// <summary>
        /// Initializes a new instance of the SeasonStandingsController class
        /// </summary>
        /// <param name="service"></param>
        /// <param name="sharedService"></param>
        public SeasonStandingsController(ISeasonStandingsService service, ISharedService sharedService)
        {
            _service = service;
            _sharedService = sharedService;
        }

        #endregion Constructors & Finalizers

        #region Actions

        // GET: SeasonStandings
        public async Task<ActionResult> Index(int? seasonID, bool? groupByDivision)
        {
            try
            {
                var seasons = await _sharedService.GetSeasonsOrderedAsync();
                _service.SetSelectedSeason(seasons, seasonID);
                ViewBag.SeasonID = new SelectList(seasons, "ID", "ID", SeasonStandingsService.SelectedSeason);

                if (groupByDivision == null)
                {
                    groupByDivision = false;
                }

                ViewBag.GroupByDivision = groupByDivision;

                var seasonStandingsResults =
                    _service.GetSeasonStandings(SeasonStandingsService.SelectedSeason, groupByDivision);

                return View(seasonStandingsResults);
            }
            catch (Exception ex)
            {
                Log.Error("Exception in SeasonStandingsController.Index: " + ex.Message);
                throw;
            }
        }

        #endregion Actions
    }
}

EldredBrown.ProFootball.AspNet.MvcWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Football Predictor App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"4611cfdd-28dd-4339-b4c1-5a69b781076a"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Football Predictor App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Teams", "Index", "TeamSeasons")</li>
                    <li>@Html.ActionLink("Games", "Index", "Games")</li>
                    <li>@Html.ActionLink("Standings", "Index", "SeasonStandings")</li>
                    <li>@Html.ActionLink("Predict Game", "PredictGame", "GamePredictor")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Football Predictor App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>